# -*- coding: utf-8 -*-
"""TimothyWalkerCodeLKC2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O8zBKq3pYHmJ3uJmG8wNOJZ2wB-7MTY_

This is knowledge check 2 for Code Louisville Data analytics 1 for the May 2022 cohort. This knowledge check shows the ability to read data from a csv file and plot the data in graphical form using seaborn or matplotlib.

File read uing Pandas:
"""

import pandas as pd

bikeData = pd.read_csv('/content/assets/bike_details.csv')
print(bikeData)

"""File read using CSV:"""

import csv

with open('/content/assets/bike_details.csv') as csvfile:
    bikereader = csv.reader(csvfile, delimiter= ',')
    rows = list(bikereader)
    for row in rows[:2]:
      print(', '.join(row))

import seaborn as sns

sns.scatterplot(x=bikeData['name'],
                y=bikeData['selling_price'])

"""Plot using matplotlib:"""

import matplotlib.pyplot as plt

plt.plot(bikeData['name'],bikeData['selling_price'], '^')